import { test, expect } from '@playwright/test';

test("", async({page})=>{
    await page.goto('https://tejffqa.nimapinfotech.in/')
await page.getByRole('link', { name: 'Operations' }).click();
await page.getByRole('link', { name: 'Shipment List-View' }).click();
await page.getByText('SHP-AC-116/').click();
await expect(page.locator('button:has-text("MAWB")')).toBeVisible();

await page.getByTestId('mawb.carrierId').click();
await page.getByRole('option', { name: '0B - Blue Air' }).click();
await page.getByRole('textbox', { name: 'MAWB Number' }).click();
await page.getByRole('textbox', { name: 'MAWB Number' }).fill('A001');
await page.locator('.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium._arrowButton_1ppeo_1').first().click();
await page.locator('[id="mawb.shipperName"]').click();
await page.locator('[id="mawb.shipperName"]').fill('ABC');
await page.getByRole('textbox', { name: 'Shipper Account No.' }).click();
await page.getByRole('textbox', { name: 'Shipper Account No.' }).fill('129293899823');
await page.locator('[id="mawb.shipperAddressLine1"]').click();
await page.locator('[id="mawb.shipperAddressLine1"]').fill('abc');
await page.locator('[id="mawb.shipperAddressLine2"]').click();
await page.locator('[id="mawb.shipperAddressLine2"]').fill('abc');
await page.locator('[id="mawb.shipperPlaceCity"]').click();
await page.locator('[id="mawb.shipperPlaceCity"]').fill('Hello');
await page.locator('[id="mawb.shipperZipCode"]').click();
await page.locator('[id="mawb.shipperZipCode"]').fill('416006');
await page.locator('[id="mawb.shipperProvinceState"]').click();
await page.locator('[id="mawb.shipperProvinceState"]').fill('aansjc');
await page.getByTestId('mawb.shipperCountry').click();
await page.getByTestId('mawb.shipperCountry').fill('India');
await page.getByRole('option', { name: 'India', exact: true }).click();
await page.locator('[id="mawb.shipperPhone"]').click();
await page.locator('[id="mawb.shipperPhone"]').fill('892389');
await page.locator('[id="mawb.shipperEmail"]').click();
await page.locator('[id="mawb.shipperEmail"]').fill('adnas@najs.co');
await page.locator('[id="mawb.consigneeName"]').click();
await page.locator('[id="mawb.consigneeName"]').fill('jacaj');
await page.getByRole('textbox', { name: 'Consignee Account No.' }).click();
await page.getByRole('textbox', { name: 'Consignee Account No.' }).fill('8923883');
await page.locator('[id="mawb.consigneeAddressLine1"]').click();
await page.locator('[id="mawb.consigneeAddressLine1"]').fill('ajsbcj');
await page.locator('[id="mawb.consigneeAddressLine2"]').click();
await page.locator('[id="mawb.consigneeAddressLine2"]').fill('kjb');
await page.locator('[id="mawb.consigneePlaceCity"]').click();
await page.locator('[id="mawb.consigneePlaceCity"]').fill('kjabc');
await page.locator('[id="mawb.consigneeZipCode"]').click();
await page.locator('[id="mawb.consigneeZipCode"]').fill('1832893');
await page.locator('[id="mawb.consigneeProvinceState"]').click();
await page.locator('[id="mawb.consigneeProvinceState"]').fill('kbx');
await page.locator('div:nth-child(3) > ._formGrid_1rvwv_65 > div:nth-child(7) > ._inputControl_p8dtq_1 > .MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root').click();
await page.getByTestId('mawb.consigneeCountry').fill('India');
await page.getByRole('option', { name: 'India', exact: true }).click();
await page.locator('[id="mawb.consigneePhone"]').click();
await page.locator('[id="mawb.consigneePhone"]').fill('23932');
await page.locator('[id="mawb.consigneeFax"]').click();
await page.locator('[id="mawb.consigneeFax"]').fill('9392');
await page.locator('[id="mawb.consigneeEmail"]').click();
await page.locator('[id="mawb.consigneeEmail"]').fill('ajbs@ajsc.co');
await page.locator('[id="mawb.agentName"]').click();
await page.locator('[id="mawb.agentName"]').fill('Abc');
await page.getByRole('textbox', { name: 'Agent\'s IATA Code' }).click();
await page.getByRole('textbox', { name: 'Agent\'s IATA Code' }).fill('i23939');
await page.locator('[id="mawb.agentAddressLine1"]').click();
await page.locator('[id="mawb.agentAddressLine1"]').fill('kajs');
await page.locator('[id="mawb.agentAddressLine2"]').click();
await page.locator('[id="mawb.agentAddressLine1"]').fill('kajsakjsbc');
await page.locator('[id="mawb.agentAddressLine2"]').click();
await page.locator('[id="mawb.agentAddressLine2"]').fill('qkjb');
await page.locator('[id="mawb.agentPlaceCity"]').click();
await page.locator('[id="mawb.agentPlaceCity"]').fill('kjabs');
await page.locator('[id="mawb.agentZipCode"]').click();
await page.locator('[id="mawb.agentZipCode"]').fill('1299023');
await page.locator('[id="mawb.agentProvinceState"]').click();
await page.locator('[id="mawb.agentProvinceState"]').fill('ajshbc');
await page.getByTestId('mawb.agentCountry').click();
await page.getByTestId('mawb.agentCountry').fill('India');
await page.getByRole('option', { name: 'India', exact: true }).click();
await page.locator('[id="mawb.agentPhone"]').click();
await page.locator('[id="mawb.agentPhone"]').fill('238993');
await page.locator('[id="mawb.agentFax"]').click();
await page.locator('[id="mawb.agentFax"]').fill('x');
await page.locator('[id="mawb.agentFax"]').click();
await page.locator('[id="mawb.agentFax"]').fill('d');
await page.locator('[id="mawb.agentEmail"]').click();
await page.locator('[id="mawb.agentEmail"]').fill('ubwdeu@asuc.co');
await page.getByTestId('mawb.originAirport').click();
await page.getByTestId('mawb.originAirport').fill('BOM');
await page.getByRole('option', { name: 'BOM - Chhatrapati Shivaji' }).click();

await page.getByRole('textbox', { name: 'Airport of Departure (on AWB)' }).click();
await page.getByRole('textbox', { name: 'Airport of Departure (on AWB)' }).fill('jasc');
await page.getByTestId('mawb.destinationAirport').click();
await page.getByRole('option', { name: 'MAG - Madang Airport' }).click();
await page.getByRole('textbox', { name: 'Airport of Destination (on' }).fill('akjsnx');
await page.getByTestId('mawb.agent').click();
await page.getByRole('option', { name: 'Sanket imp' }).click();
await page.locator('[id="_r_bf_"]').click();
await page.getByText('No options').click();
await page.getByText('No options').click();
await page.getByTestId('mawb.coLoader').click();
await page.getByRole('option', { name: 'Sanket imp' }).click();
await page.getByRole('textbox', { name: 'Flight Number' }).click();
await page.getByRole('textbox', { name: 'Flight Number' }).fill('jkqw92832388');
await page.getByRole('textbox', { name: 'Flight Number' }).dblclick();
await page.getByRole('textbox', { name: 'Flight Number' }).click();
await page.getByRole('textbox', { name: 'Requested Routing' }).click();
await page.getByRole('textbox', { name: 'Requested Routing' }).fill('2893');
await page.locator('._routingRow_1rvwv_268 > div > .MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root > .MuiAutocomplete-endAdornment').first().click();
});