import { test, expect } from '@playwright/test';

test("", async({page})=>{
   await page.goto('https://tejffqa.nimapinfotech.in/login');
   await page.getByTestId('email').click();
   await page.getByTestId('email').fill('DEM-27');
   await page.getByRole('textbox', { name: 'Password *' }).click();
   await page.getByRole('textbox', { name: 'Password *' }).fill('DEMp7738');
   await page.getByRole('button', { name: 'Sign in' }).click();
   await page.getByRole('link', { name: 'Operations' }).click();
   await page.getByRole('button', { name: 'New Shipment' }).click();

   await expect(page.getByRole('tab', { name: 'HAWB' })).toBeVisible();
   await page.getByRole('tab', { name: 'HAWB' }).click();
   await page.getByRole('textbox', { name: 'HAWB Number' }).click();
   await page.getByRole('textbox', { name: 'HAWB Number' }).fill('H938995');
   await page.locator('[id="hawb.shipperName"]').click();
   await page.locator('[id="hawb.shipperName"]').fill('XYZ');
   await page.locator('[id="hawb.consigneeName"]').click();
   await page.locator('[id="hawb.consigneeName"]').fill('XYZ');
   await page.locator('[id="hawb.notifyName"]').click();
   await page.getByRole('button', { name: 'Copy Consignee' }).click();
   await page.locator('div').filter({ hasText: /^Nature and Quantity of Goods$/ }).first().click();
   await page.locator('[id="hawb.goodsDescription"]').fill('akjsncj');
   await page.locator('[id="hawb.marksAndNumbers"]').click();
   await page.locator('[id="hawb.marksAndNumbers"]').fill('jadcjwe');
   await page.locator('div:nth-child(4) > ._sectionTitle_1tpst_53 > .MuiButtonBase-root').click();
   await page.getByRole('combobox').nth(2).click();
   await page.getByRole('option', { name: 'Indian Rupee' }).click();
   await page.getByTestId('hawb.chargeCode').click();
   await page.getByRole('option', { name: 'FC - FREIGHT_CHARGE' }).click();
   await page.getByRole('combobox').nth(4).click();
   await page.getByRole('combobox').nth(4).click();
   await page.getByRole('combobox').nth(4).fill('123');
   await page.getByRole('combobox').nth(5).click();
   await page.getByRole('textbox', { name: 'Declared Value for Carriage' }).click();
   await page.getByRole('textbox', { name: 'Declared Value for Carriage' }).fill('sncwjn');
   await page.getByRole('textbox', { name: 'Declared Value for Customs' }).click();
   await page.getByRole('textbox', { name: 'Declared Value for Customs' }).fill('aknc');
   await page.getByRole('textbox', { name: 'Amount of Insurance' }).click();
   await page.getByRole('textbox', { name: 'Amount of Insurance' }).fill('129392');
   await page.getByRole('textbox', { name: 'Weight Charge' }).click();
   await page.getByRole('textbox', { name: 'Weight Charge' }).fill('1223');
   await page.getByRole('textbox', { name: 'Valuation Charge' }).click();
   await page.getByRole('textbox', { name: 'Valuation Charge' }).fill('233');
   await page.getByRole('textbox', { name: 'Tax' }).click();
   await page.getByRole('textbox', { name: 'Tax' }).fill('12');
   await page.locator('div:nth-child(5) > ._sectionTitle_1tpst_53 > .MuiButtonBase-root').click();
   await page.getByRole('textbox', { name: 'Special Service Information' }).click();
   await page.getByRole('textbox', { name: 'Special Service Information' }).fill('ancn');
   await page.getByRole('textbox', { name: 'Other Service Information' }).click();
   await page.getByRole('textbox', { name: 'Other Service Information' }).fill('ansc');
   await page.getByRole('textbox', { name: 'SCI' }).click();
   await page.getByRole('textbox', { name: 'Other Service Information' }).fill('anscansc');
   await page.getByRole('textbox', { name: 'SCI' }).click();
   await page.getByRole('textbox', { name: 'SCI' }).fill('ajksnc');
   await page.getByTestId('hawb.specialHandlingCodes').click();
   await page.getByTestId('hawb.specialHandlingCodes').fill('');
   await page.getByText('HAWB Number PartiesShipperName ConsigneeName NotifyName Copy ConsigneeNature').click();
   await page.locator('div:nth-child(6) > ._sectionTitle_1tpst_53 > .MuiButtonBase-root').click();
   await page.getByRole('textbox', { name: 'Reference Number' }).click();
   await page.getByRole('textbox', { name: 'Reference Number' }).fill('q912239');
   await page.getByRole('textbox', { name: 'Additional Reference Info' }).click();
   await page.getByRole('textbox', { name: 'Additional Reference Info' }).fill('knwejksn');
   await page.getByRole('textbox', { name: 'Booking No.' }).click();
   await page.getByRole('textbox', { name: 'Booking No.' }).fill('aksnkj');
   await page.getByRole('textbox', { name: 'Shipper Reference No.' }).click();
   await page.getByRole('textbox', { name: 'Shipper Reference No.' }).fill('ij233');
   await page.getByRole('textbox', { name: 'Forwarder Reference No.' }).click();
   await page.getByRole('textbox', { name: 'Forwarder Reference No.' }).fill('an c');
   await page.getByRole('textbox', { name: 'ITN / MRN / DU-E' }).click();
   await page.getByRole('textbox', { name: 'ITN / MRN / DU-E' }).fill('a c');
   await page.getByRole('textbox', { name: 'Purchase Order No.' }).click();
   await page.getByRole('textbox', { name: 'Purchase Order No.' }).fill('anscjn');
   await page.getByRole('textbox', { name: 'SPO No.' }).click();
   await page.getByRole('textbox', { name: 'SPO No.' }).fill('an c');
   await page.getByRole('textbox', { name: 'Exporter Reference No.' }).click();
   await page.getByRole('textbox', { name: 'Exporter Reference No.' }).fill('an c');
   await page.getByRole('textbox', { name: 'Consignee Order No.' }).click();
   await page.getByRole('textbox', { name: 'Consignee Order No.' }).fill('ansnn');
   await page.getByRole('textbox', { name: 'Invoice Reference No.' }).click();
   await page.getByRole('textbox', { name: 'Invoice Reference No.' }).fill('asciuj');
   await page.getByRole('textbox', { name: 'Customs Broker Reference No.' }).click();
   await page.getByRole('textbox', { name: 'Customs Broker Reference No.' }).fill('akjodijw');
   await page.getByRole('textbox', { name: 'Contract No.' }).click();
   await page.getByRole('textbox', { name: 'Contract No.' }).fill('kajnjwe');
   await page.getByRole('textbox', { name: 'Letter of Credit No.' }).click();
   await page.getByRole('textbox', { name: 'Letter of Credit No.' }).fill('alsmiwj12');
   await page.getByTestId('hawb.letterOfCreditIssueDate-wrapper').getByRole('button', { name: 'Choose date' }).click();
   await page.getByRole('gridcell', { name: '1', exact: true }).click();
   await page.getByTestId('hawb.letterOfCreditExpiryDate-wrapper').getByRole('button', { name: 'Choose date' }).click();
   await page.getByRole('gridcell', { name: '2', exact: true }).click();
   await page.getByRole('textbox', { name: 'Export License No.' }).click();
   await page.getByRole('textbox', { name: 'Export License No.' }).fill('aksncnw');
   await page.getByTestId('hawb.exportLicenseIssueDate-wrapper').getByRole('spinbutton', { name: 'Month' }).click();
   await page.getByTestId('hawb.exportLicenseIssueDate-wrapper').getByRole('button', { name: 'Choose date' }).click();
   await page.getByRole('gridcell', { name: '13' }).click();
   await page.getByTestId('hawb.exportLicenseExpiryDate-wrapper').getByRole('group').click();
   await page.getByTestId('hawb.exportLicenseExpiryDate-wrapper').getByRole('spinbutton', { name: 'Day' }).fill('2');
   await page.getByTestId('hawb.exportLicenseExpiryDate-wrapper').getByRole('spinbutton', { name: 'Month' }).fill('2');
   await page.getByTestId('hawb.exportLicenseExpiryDate-wrapper').getByRole('spinbutton', { name: 'Year' }).fill('3');
   await page.locator('div:nth-child(7) > ._sectionTitle_1tpst_53 > .MuiButtonBase-root').click();
   await page.locator('[id="hawb.signatureOfShipper"]').click();
   await page.locator('[id="hawb.signatureOfShipper"]').fill('ijdw');
   await page.getByTestId('hawb.issuedOn-wrapper').getByRole('button', { name: 'Choose date' }).click();
   await page.getByRole('gridcell', { name: '28' }).click();
   await page.getByRole('gridcell', { name: '28' }).click();
   await page.getByRole('textbox', { name: 'Issue Location' }).fill('askd');
   await page.getByRole('textbox', { name: 'Signature of Issuing Carrier' }).click();
   await page.getByRole('button', { name: 'Current User' }).click();
   await page.locator('[id="hawb.remarks"]').click();
   await page.locator('[id="hawb.remarks"]').fill('aowe');
});